name: DragonCore
version: '1.0.1'
main: fur.kiyoshi.dragoncore.Main
api-version: 1.19
authors: [ MyNameIsKiyoshi, WhiXard ]
softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.

commands:
  about:
    description: "Send the plugin info"
    usage: /about
    permission: default
  heal:
    description: "Heals the player"
    usage: /heal
    permission: dragoncore.heal
  fly:
    description: "Flight"
    usage: /fly
    permission: dragoncore.fly
  horse:
    description: "Spawns the H O R S E"
    usage: /horse
    permission: dragoncore.fun.horse
  tp:
    description: "Teleport"
    usage: /tp <player>
    permission: dragoncore.tp
  tpa:
    description: "Teleport Request"
    usage: /tpa <player>
    permission: dragoncore.tpa
  staff:
    description: "Staff Mode"
    usage: /staff
    permission: dragoncore.staff
  stafflist:
    description: "List of staff"
    usage: /stafflist
    permission: dragoncore.stafflist
  help:
    description: "Help"
    usage: /help
    permission: dragoncore.help
  staffmode:
    description: "Staff Mode"
    usage: /staffmode
    permission: dragoncore.staffmode
  bloodmoonstatus:
    description: "Bloodmoon Status"
    usage: /bloodmoonstatus
    permission: dragoncore.bloodmoonstatus