name: DragonCore
version: '1.0.1'
main: fur.kiyoshi.dragoncore.Main
api-version: 1.19
authors: [ MyNameIsKiyoshi ]

commands:
  about:
    description: "Send the plugin info"
    usage: /about
    permission: default
  heal:
    description: "Heals the player"
    usage: /heal
    permission: dragoncore.heal
  fly:
    description: "Flight"
    usage: /fly
    permission: dragoncore.fly
  horse:
    description: "Spawns the H O R S E"
    usage: /horse
    permission: dragoncore.fun.horse